[package]
name = "bid_smt"
type = "bin"
authors = ["workingdoge"]
compiler_version = ">0.19.0"

[dependencies]
smt_bn254 = { tag = "v0.1.0", git = "https://github.com/workingdoge/zk-kit", directory = "packages/circuits/noir/crates/smt_bn254" }
ecrecover = { path = "../../../../ecrecover-noir/" }
#ecrecover = { tag = "v0.19.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
